#**Maestría en Inteligencia Artificial Aplicada**
##**Curso: Inteligencia Artificial y Aprendizaje Automático**
###Tecnológico de Monterrey
###Prof Luis Eduardo Falcón Morales

## **Adtividad de la Semana 10**
###**Reducción de Dimensionalidad - Descomposición en Valores Singulares (SVD) y Sistemas de Recomendación**

**Nombres y matrículas de los integrantes del equipo:**

*   Jose Salvador Ortiz Sainz de Rozas - A01095149
*   Juan Carlos Alvarado Carricarte - A01793486
*   Rogelio Chávez López - A01794226
*   Sergio López Madriz - A01064725
*   Hansel Zapiain Rodríguez - A00469031

En cada sección deberás incluir todas las líneas de código necesarias para responder a cada uno de los ejercicios.

In [1]:
import numpy as np
import pandas as pd

from sklearn.decomposition import TruncatedSVD

#**Ejercicio-1.**

In [2]:
ratings = pd.read_csv('rating_final.csv')
ratings.head()

  userID  placeID  rating  food_rating  service_rating
0  U1077   135085       2            2               2
1  U1077   135038       2            2               1
2  U1077   132825       2            2               2
3  U1077   135060       1            2               2
4  U1068   135104       1            1               2

In [3]:
ratings.shape

(1161, 5)

In [4]:
restaurantes = pd.read_csv('geoplaces2.csv', encoding='latin-1')
restaurantes = restaurantes[['placeID','name']]
restaurantes.head()

   placeID                            name
0   134999                 Kiku Cuernavaca
1   132825                 puesto de tacos
2   135106      El Rincón de San Francisco
3   132667  little pizza Emilio Portes Gil
4   132613                   carnitas_mata

In [5]:
full_df = pd.merge(ratings, restaurantes, on='placeID')
full_df.head(10)

  userID  placeID  rating  food_rating  service_rating                    name
0  U1077   135085       2            2               2  Tortas Locas Hipocampo
1  U1108   135085       1            2               1  Tortas Locas Hipocampo
2  U1081   135085       1            2               1  Tortas Locas Hipocampo
3  U1056   135085       2            2               2  Tortas Locas Hipocampo
4  U1134   135085       2            1               2  Tortas Locas Hipocampo
5  U1116   135085       2            2               2  Tortas Locas Hipocampo
6  U1132   135085       2            2               2  Tortas Locas Hipocampo
7  U1120   135085       0            0               0  Tortas Locas Hipocampo
8  U1036   135085       2            2               2  Tortas Locas Hipocampo
9  U1084   135085       2            2               2  Tortas Locas Hipocampo

In [6]:
full_df.shape

(1161, 6)

In [7]:
Utility_Matrix = full_df.pivot_table(values='rating', index='userID', columns='name', fill_value=0)
Utility_Matrix.head(10)

name,Abondance Restaurante Bar,Arrachela Grill,Cabana Huasteca,Cafe Chaires,Cafeteria cenidet,Cafeteria y Restaurant El Pacifico,Carls Jr,Carnitas Mata Calle 16 de Septiembre,Carreton de Flautas y Migadas,Cenaduria El RincÃ³n de Tlaquepaque,...,puesto de tacos,rockabilly,shi ro ie,sirloin stockade,tacos abi,tacos de barbacoa enfrente del Tec,tacos de la estacion,tacos los volcanes,tortas hawai,vips
userID,,,,,,,,,,,,,,,,,,,,,
U1001,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
U1002,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
U1003,0,0,2,0,0,0,0,0,0,0,...,2,2,0,0,0,0,0,0,0,0
U1004,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,2,0,0
U1005,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1006,0,0,0,1,0,0,0,0,0,0,...,1,0,2,0,0,0,0,0,0,0
U1007,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1008,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1009,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
U1010,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
Utility_Matrix.shape

(138, 129)

#**Ejercicio-2.**

In [9]:
print('Total de elementos de la matriz de utilidad: %d' % (Utility_Matrix.size))
print('Total de elementos diferentes de cero: %d' % (np.count_nonzero(Utility_Matrix)))
print('Porcentaje de elementos diferentes de cero: %.1f%%' % (100 * np.count_nonzero(Utility_Matrix) / Utility_Matrix.size))

Total de elementos de la matriz de utilidad: 17802
Total de elementos diferentes de cero: 907
Porcentaje de elementos diferentes de cero: 5.1%

#**Ejercicio-3.**

In [10]:
X = Utility_Matrix.T     # Tomamos la traspuesta para que los renglones sean las películas y las columnas los usuarios.
X.shape

num_sv = 128

SVD = TruncatedSVD(n_components=num_sv, random_state=1)

resultant_matrix = SVD.fit_transform(X)
resultant_matrix.shape

corrMx = np.corrcoef(resultant_matrix, )
corrMx.shape

(129, 129)

In [11]:
restaurante = 'Subway'

names = Utility_Matrix.columns
names_list = list(names)
id_megusta = names_list.index(restaurante)

corr_recomienda = corrMx[id_megusta]
print(names)
print(id_megusta)
print(corr_recomienda.shape)
print(corr_recomienda)

Index(['Abondance Restaurante Bar', 'Arrachela Grill', 'Cabana Huasteca',
       'Cafe Chaires', 'Cafeteria cenidet',
       'Cafeteria y Restaurant El Pacifico', 'Carls Jr',
       'Carnitas Mata  Calle 16 de Septiembre',
       'Carreton de Flautas y Migadas', 'Cenaduria El RincÃ³n de Tlaquepaque',
       ...
       'puesto de tacos', 'rockabilly ', 'shi ro ie', 'sirloin stockade',
       'tacos abi', 'tacos de barbacoa enfrente del Tec',
       'tacos de la estacion', 'tacos los volcanes', 'tortas hawai', 'vips'],
      dtype='object', name='name', length=129)
88
(129,)
[-7.75041211e-04 -7.93980123e-05 -5.31511041e-03  8.65224332e-04
 -3.06277628e-03  4.00602822e-05 -1.56031818e-03 -5.33543641e-03
  7.33208504e-04 -1.56312245e-03 -1.85927581e-03  3.01087201e-01
 -3.09337773e-05 -3.69524527e-03 -2.29811856e-03 -1.72309544e-03
  2.69055573e-03  4.62051313e-04 -2.13106062e-03 -6.25389640e-03
  3.36896172e-03  1.16585577e-01  1.88544995e-03  2.55671923e-03
 -5.53156435e-03 -2.93574906e-03  2.04414020e-03 -1.37676055e-03
 -2.03275693e-03  1.12043338e-01 -2.38087476e-03  6.57257880e-04
  3.56276376e-03 -3.65648031e-03  1.70388809e-03 -4.55405776e-03
 -2.10940967e-03  2.34619472e-01 -3.83408820e-03 -5.15847035e-04
 -2.28928844e-03  3.88169611e-01 -2.09051986e-03 -2.31226939e-03
  1.33602565e-03  3.00998500e-01  1.71412701e-01 -3.32306775e-03
 -4.78231748e-03 -8.08802818e-04 -2.67150753e-03  1.12003673e-01
 -3.94161321e-03 -2.07986371e-03  1.15990948e-01  2.27869279e-01
  4.31690905e-04 -8.76540610e-04  6.09522822e-01 -6.48498621e-03
  4.25459856e-01 -2.29037157e-03  4.49406440e-05  5.15276275e-04
  2.85156112e-01 -1.91498223e-03 -4.19396330e-03 -5.65833563e-03
 -2.59715013e-03 -3.75816857e-03 -6.10818008e-03  1.42150745e-03
 -1.59915763e-04 -1.95636687e-03  2.11599894e-03 -2.11817865e-03
 -4.42450499e-03 -2.31266714e-03  7.82077249e-04 -2.98449079e-03
 -2.84260190e-03 -8.64078593e-04 -1.51435143e-03 -3.22108600e-03
 -2.58410839e-03  4.29850653e-01  4.17211438e-01  3.92128905e-03
  1.00000000e+00 -1.00158477e-03  8.67088804e-04 -2.81725163e-03
  2.39298959e-04 -3.08621674e-03  1.37530374e-03  2.68563671e-04
  2.94958703e-03  5.06308344e-01 -3.23374182e-03 -8.42871497e-04
 -3.74931996e-03  1.61910260e-03 -1.26982728e-03 -2.59650467e-03
  1.71766330e-03 -2.45534462e-03 -1.14754411e-03  1.92697337e-03
 -3.60581095e-03 -2.42976955e-03 -8.67053037e-03  3.36387106e-03
  3.02734274e-03  2.49708210e-03  1.39356691e-03 -1.60894298e-05
 -8.43611689e-04 -1.75352968e-03 -1.21285572e-03 -3.59462396e-03
 -2.39955913e-03 -4.95237324e-06 -3.22539526e-03  1.82957639e-03
  2.47353778e-03 -2.58638452e-03 -2.90361676e-03 -1.92712154e-03
  8.44380091e-04]

In [12]:
sorted_index_array = np.argsort(corr_recomienda)
sorted_array = corr_recomienda[sorted_index_array]
rslt = sorted_array[-11 : -1][::-1]
best_rest = sorted_index_array[-11 : -1][::-1]
print("{} mejores calificaciones:".format(10),
      rslt)
print("{} mejores restaurantes:".format(10),
      best_rest)

10 mejores calificaciones: [0.60952282 0.50630834 0.42985065 0.42545986 0.41721144 0.38816961
 0.3010872  0.3009985  0.28515611 0.23461947]
10 mejores restaurantes: [58 97 85 60 86 41 11 45 64 37]

In [13]:
sub_reco_rating = list(names[best_rest])
print(sub_reco_rating)

['Restaurant Teely', 'Vips', 'Rincon del Bife', 'Restaurant and Bar and Clothesline Carlos N Charlies', 'Sanborns Casa Piedra', 'Mariscos Tia Licha', 'Chilis Cuernavaca', 'Mikasa', 'Restaurant los Pinos', 'Log Yin']

#**Ejercicio-4.**

In [19]:
print('Total de elementos de la matriz de utilidad: %d' % (Utility_Matrix[sub_reco_rating].size))
print('Total de elementos diferentes de cero: %d' % (np.count_nonzero(Utility_Matrix[sub_reco_rating])))
print('Porcentaje de elementos diferentes de cero: %.1f%%' % (100 * np.count_nonzero(Utility_Matrix[sub_reco_rating]) / Utility_Matrix[sub_reco_rating].size))

Total de elementos de la matriz de utilidad: 1380
Total de elementos diferentes de cero: 43
Porcentaje de elementos diferentes de cero: 3.1%

#**Ejercicio-5.**

In [20]:
restaurante = 'tacos de barbacoa enfrente del Tec'

names = Utility_Matrix.columns
names_list = list(names)
id_megusta = names_list.index(restaurante)

corr_recomienda = corrMx[id_megusta]
print(names)
print(id_megusta)
print(corr_recomienda.shape)
print(corr_recomienda)

Index(['Abondance Restaurante Bar', 'Arrachela Grill', 'Cabana Huasteca',
       'Cafe Chaires', 'Cafeteria cenidet',
       'Cafeteria y Restaurant El Pacifico', 'Carls Jr',
       'Carnitas Mata  Calle 16 de Septiembre',
       'Carreton de Flautas y Migadas', 'Cenaduria El RincÃ³n de Tlaquepaque',
       ...
       'puesto de tacos', 'rockabilly ', 'shi ro ie', 'sirloin stockade',
       'tacos abi', 'tacos de barbacoa enfrente del Tec',
       'tacos de la estacion', 'tacos los volcanes', 'tortas hawai', 'vips'],
      dtype='object', name='name', length=129)
124
(129,)
[ 1.91858219e-03  1.96546468e-04  1.31573341e-02 -2.14182675e-03
  7.58177494e-03 -9.91675579e-05  3.86250259e-03  1.32076503e-02
  4.07791379e-01  3.86944443e-03  4.60255973e-03  1.57376799e-03
  7.65752756e-05  9.14742555e-03  5.68889665e-03  4.26545089e-03
 -6.66035849e-03 -1.14378875e-03  5.27535168e-03  1.54812597e-02
 -8.33972423e-03  4.86222016e-03 -4.66735272e-03 -6.32905183e-03
  1.48570138e-01  1.91187712e-01 -5.06018380e-03  3.40811331e-03
  5.03200501e-03  5.61185182e-03  5.89375616e-03 -1.62701447e-03
 -8.81947310e-03  9.05146450e-03 -4.21790391e-03  1.12733800e-02
  2.58530460e-01  1.28241099e-02  9.49112543e-03  1.27695782e-03
  5.66703806e-03  5.78917234e-03  5.17499473e-03  5.72392643e-03
 -3.30727578e-03  1.85129087e-03  1.12275691e-02  8.22611562e-03
  1.18384275e-02  2.00215764e-03  6.61320546e-03  5.74472677e-03
  9.75729911e-03  5.14861588e-03  6.90866253e-03 -3.46758711e-03
 -1.06863283e-03  2.16983972e-03  1.34152599e-04  1.60533129e-02
  6.53933503e-03  5.66971929e-03 -1.11248690e-04 -1.27554493e-03
 -1.68477068e-03  4.74045864e-03  1.03819812e-02  1.40069739e-02
  6.42913682e-03  9.30318956e-03  1.51205450e-02 -3.51888242e-03
  3.95864802e-04  4.84290460e-03 -5.23806713e-03  5.24346292e-03
  1.09526776e-02  5.72491104e-03 -1.93599961e-03  7.38798249e-03
  7.03674246e-03  2.13899052e-03  3.74871380e-03  7.97366404e-03
  6.39685254e-03 -5.45147351e-03  4.41719772e-03 -9.70698750e-03
  2.47353778e-03  2.47938133e-03 -2.14644217e-03  6.97398892e-03
  4.37190089e-01  7.63980081e-03 -3.40450704e-03 -6.64818167e-04
 -7.30157969e-03  1.55370688e-02  8.00499300e-03  2.08649324e-03
  1.71024798e-01  1.70830669e-01  3.14340446e-03  6.42753901e-03
 -4.25200387e-03  6.07810319e-03  2.84069758e-03 -4.77014220e-03
  8.92603461e-03  6.01479318e-03  2.14635363e-02 -8.32712250e-03
 -7.49406068e-03 -6.18142260e-03  6.53842970e-01  3.98287124e-05
  1.95195447e-01  4.34078959e-03  4.12799949e-01  8.89834168e-03
  5.94000854e-03  1.22593934e-05  7.98433145e-03  6.65294685e-01
  1.00000000e+00  6.40248701e-03  7.18778219e-03  4.77050901e-03
  8.17194436e-01]

In [21]:
sorted_index_array = np.argsort(corr_recomienda)
sorted_array = corr_recomienda[sorted_index_array]
rslt = sorted_array[-11 : -1][::-1]
best_rest = sorted_index_array[-11 : -1][::-1]
print("{} mejores calificaciones:".format(10),
      rslt)
print("{} mejores restaurantes:".format(10),
      best_rest)

10 mejores calificaciones: [0.81719444 0.66529468 0.65384297 0.43719009 0.41279995 0.40779138
 0.25853046 0.19519545 0.19118771 0.1710248 ]
10 mejores restaurantes: [128 123 114  92 118   8  36 116  25 100]

In [22]:
tacos_reco = list(names[best_rest])
print(tacos_reco)

['vips', 'tacos abi', 'little pizza Emilio Portes Gil', 'Taqueria EL amigo ', 'puesto de gorditas', 'Carreton de Flautas y Migadas', 'Little Cesarz', 'palomo tec', 'Hamburguesas La perica', 'carnitas mata calle Emilio Portes Gil']

Conclusiones: Es esperado que todos los restaurantes recomendados estén intricamente relacionados a soluciones de comida pragmática y/ económica por el giro del restuarante de interés.

#**Ejercicio-6.**

In [23]:
Utility_Matrix_food = full_df.pivot_table(values='food_rating', index='userID', columns='name', fill_value=0)
Utility_Matrix_food.head(10)

name,Abondance Restaurante Bar,Arrachela Grill,Cabana Huasteca,Cafe Chaires,Cafeteria cenidet,Cafeteria y Restaurant El Pacifico,Carls Jr,Carnitas Mata Calle 16 de Septiembre,Carreton de Flautas y Migadas,Cenaduria El RincÃ³n de Tlaquepaque,...,puesto de tacos,rockabilly,shi ro ie,sirloin stockade,tacos abi,tacos de barbacoa enfrente del Tec,tacos de la estacion,tacos los volcanes,tortas hawai,vips
userID,,,,,,,,,,,,,,,,,,,,,
U1001,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
U1002,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
U1003,0,0,2,0,0,0,0,0,0,0,...,2,2,0,0,0,0,0,0,0,0
U1004,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,2,0,0
U1005,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1006,0,0,0,0,0,0,0,0,0,0,...,1,0,2,0,0,0,0,0,0,0
U1007,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1008,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1009,0,0,2,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
U1010,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
X_food = Utility_Matrix_food.T     # Tomamos la traspuesta para que los renglones sean las películas y las columnas los usuarios.
X_food.shape

num_sv = 128

SVD = TruncatedSVD(n_components=num_sv, random_state=1)

resultant_matrix = SVD.fit_transform(X_food)
resultant_matrix.shape

corrMx_food = np.corrcoef(resultant_matrix, )
corrMx_food.shape

(129, 129)

In [25]:
restaurante = 'Subway'

names = Utility_Matrix_food.columns
names_list = list(names)
id_megusta = names_list.index(restaurante)

corr_recomienda_food = corrMx_food[id_megusta]
print(names)
print(id_megusta)
print(corr_recomienda.shape)
print(corr_recomienda)

Index(['Abondance Restaurante Bar', 'Arrachela Grill', 'Cabana Huasteca',
       'Cafe Chaires', 'Cafeteria cenidet',
       'Cafeteria y Restaurant El Pacifico', 'Carls Jr',
       'Carnitas Mata  Calle 16 de Septiembre',
       'Carreton de Flautas y Migadas', 'Cenaduria El RincÃ³n de Tlaquepaque',
       ...
       'puesto de tacos', 'rockabilly ', 'shi ro ie', 'sirloin stockade',
       'tacos abi', 'tacos de barbacoa enfrente del Tec',
       'tacos de la estacion', 'tacos los volcanes', 'tortas hawai', 'vips'],
      dtype='object', name='name', length=129)
88
(129,)
[ 1.91858219e-03  1.96546468e-04  1.31573341e-02 -2.14182675e-03
  7.58177494e-03 -9.91675579e-05  3.86250259e-03  1.32076503e-02
  4.07791379e-01  3.86944443e-03  4.60255973e-03  1.57376799e-03
  7.65752756e-05  9.14742555e-03  5.68889665e-03  4.26545089e-03
 -6.66035849e-03 -1.14378875e-03  5.27535168e-03  1.54812597e-02
 -8.33972423e-03  4.86222016e-03 -4.66735272e-03 -6.32905183e-03
  1.48570138e-01  1.91187712e-01 -5.06018380e-03  3.40811331e-03
  5.03200501e-03  5.61185182e-03  5.89375616e-03 -1.62701447e-03
 -8.81947310e-03  9.05146450e-03 -4.21790391e-03  1.12733800e-02
  2.58530460e-01  1.28241099e-02  9.49112543e-03  1.27695782e-03
  5.66703806e-03  5.78917234e-03  5.17499473e-03  5.72392643e-03
 -3.30727578e-03  1.85129087e-03  1.12275691e-02  8.22611562e-03
  1.18384275e-02  2.00215764e-03  6.61320546e-03  5.74472677e-03
  9.75729911e-03  5.14861588e-03  6.90866253e-03 -3.46758711e-03
 -1.06863283e-03  2.16983972e-03  1.34152599e-04  1.60533129e-02
  6.53933503e-03  5.66971929e-03 -1.11248690e-04 -1.27554493e-03
 -1.68477068e-03  4.74045864e-03  1.03819812e-02  1.40069739e-02
  6.42913682e-03  9.30318956e-03  1.51205450e-02 -3.51888242e-03
  3.95864802e-04  4.84290460e-03 -5.23806713e-03  5.24346292e-03
  1.09526776e-02  5.72491104e-03 -1.93599961e-03  7.38798249e-03
  7.03674246e-03  2.13899052e-03  3.74871380e-03  7.97366404e-03
  6.39685254e-03 -5.45147351e-03  4.41719772e-03 -9.70698750e-03
  2.47353778e-03  2.47938133e-03 -2.14644217e-03  6.97398892e-03
  4.37190089e-01  7.63980081e-03 -3.40450704e-03 -6.64818167e-04
 -7.30157969e-03  1.55370688e-02  8.00499300e-03  2.08649324e-03
  1.71024798e-01  1.70830669e-01  3.14340446e-03  6.42753901e-03
 -4.25200387e-03  6.07810319e-03  2.84069758e-03 -4.77014220e-03
  8.92603461e-03  6.01479318e-03  2.14635363e-02 -8.32712250e-03
 -7.49406068e-03 -6.18142260e-03  6.53842970e-01  3.98287124e-05
  1.95195447e-01  4.34078959e-03  4.12799949e-01  8.89834168e-03
  5.94000854e-03  1.22593934e-05  7.98433145e-03  6.65294685e-01
  1.00000000e+00  6.40248701e-03  7.18778219e-03  4.77050901e-03
  8.17194436e-01]

In [26]:
sorted_index_array = np.argsort(corr_recomienda_food)
sorted_array = corr_recomienda_food[sorted_index_array]
rslt = sorted_array[-11 : -1][::-1]
best_rest = sorted_index_array[-11 : -1][::-1]
print("{} mejores calificaciones:".format(10),
      rslt)
print("{} mejores restaurantes:".format(10),
      best_rest)

10 mejores calificaciones: [0.81641273 0.46893041 0.44212968 0.4152606  0.38179532 0.365631
 0.33169404 0.31206522 0.25034472 0.23268488]
10 mejores restaurantes: [58 60 97 41 85 86 55 46 29 54]

In [27]:
sub_reco_food = list(names[best_rest])
print(sub_reco_food)

['Restaurant Teely', 'Restaurant and Bar and Clothesline Carlos N Charlies', 'Vips', 'Mariscos Tia Licha', 'Rincon del Bife', 'Sanborns Casa Piedra', 'Restaurant Las Mananitas', 'Paniroles', 'Kiku Cuernavaca', 'Restaurant Familiar El Chino']

Conclusiones: Si bien existen coincidencias con las primeras recomendaciones, existen restaurantes adicionales por los comensales que disfrutan de la comida de la misma manera que Subway e.g. Restaurante Las Mananitas o Restaurant Familiar el Chino. Además los restaurantes pueden variar de posición por una mejor nota en servicio que en comida e.g. Vips.

#**Ejercicio-7.**

In [28]:
Utility_Matrix_service = full_df.pivot_table(values='service_rating', index='userID', columns='name', fill_value=0)
Utility_Matrix_service.head(10)

name,Abondance Restaurante Bar,Arrachela Grill,Cabana Huasteca,Cafe Chaires,Cafeteria cenidet,Cafeteria y Restaurant El Pacifico,Carls Jr,Carnitas Mata Calle 16 de Septiembre,Carreton de Flautas y Migadas,Cenaduria El RincÃ³n de Tlaquepaque,...,puesto de tacos,rockabilly,shi ro ie,sirloin stockade,tacos abi,tacos de barbacoa enfrente del Tec,tacos de la estacion,tacos los volcanes,tortas hawai,vips
userID,,,,,,,,,,,,,,,,,,,,,
U1001,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
U1002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1003,0,0,2,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
U1004,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,2,0,0
U1005,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1006,0,0,0,1,0,0,0,0,0,0,...,1,0,2,0,0,0,0,0,0,0
U1007,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1008,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1009,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
U1010,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
X_service = Utility_Matrix_service.T     # Tomamos la traspuesta para que los renglones sean las películas y las columnas los usuarios.
X_service.shape

num_sv = 128

SVD = TruncatedSVD(n_components=num_sv, random_state=1)

resultant_matrix = SVD.fit_transform(X_service)
resultant_matrix.shape

corrMx_service = np.corrcoef(resultant_matrix, )
corrMx_service.shape

(129, 129)

In [30]:
restaurante = 'Subway'

names = Utility_Matrix_service.columns
names_list = list(names)
id_megusta = names_list.index(restaurante)

corr_recomienda_serv = corrMx_service[id_megusta]
print(names)
print(id_megusta)
print(corr_recomienda.shape)
print(corr_recomienda)

Index(['Abondance Restaurante Bar', 'Arrachela Grill', 'Cabana Huasteca',
       'Cafe Chaires', 'Cafeteria cenidet',
       'Cafeteria y Restaurant El Pacifico', 'Carls Jr',
       'Carnitas Mata  Calle 16 de Septiembre',
       'Carreton de Flautas y Migadas', 'Cenaduria El RincÃ³n de Tlaquepaque',
       ...
       'puesto de tacos', 'rockabilly ', 'shi ro ie', 'sirloin stockade',
       'tacos abi', 'tacos de barbacoa enfrente del Tec',
       'tacos de la estacion', 'tacos los volcanes', 'tortas hawai', 'vips'],
      dtype='object', name='name', length=129)
88
(129,)
[ 1.91858219e-03  1.96546468e-04  1.31573341e-02 -2.14182675e-03
  7.58177494e-03 -9.91675579e-05  3.86250259e-03  1.32076503e-02
  4.07791379e-01  3.86944443e-03  4.60255973e-03  1.57376799e-03
  7.65752756e-05  9.14742555e-03  5.68889665e-03  4.26545089e-03
 -6.66035849e-03 -1.14378875e-03  5.27535168e-03  1.54812597e-02
 -8.33972423e-03  4.86222016e-03 -4.66735272e-03 -6.32905183e-03
  1.48570138e-01  1.91187712e-01 -5.06018380e-03  3.40811331e-03
  5.03200501e-03  5.61185182e-03  5.89375616e-03 -1.62701447e-03
 -8.81947310e-03  9.05146450e-03 -4.21790391e-03  1.12733800e-02
  2.58530460e-01  1.28241099e-02  9.49112543e-03  1.27695782e-03
  5.66703806e-03  5.78917234e-03  5.17499473e-03  5.72392643e-03
 -3.30727578e-03  1.85129087e-03  1.12275691e-02  8.22611562e-03
  1.18384275e-02  2.00215764e-03  6.61320546e-03  5.74472677e-03
  9.75729911e-03  5.14861588e-03  6.90866253e-03 -3.46758711e-03
 -1.06863283e-03  2.16983972e-03  1.34152599e-04  1.60533129e-02
  6.53933503e-03  5.66971929e-03 -1.11248690e-04 -1.27554493e-03
 -1.68477068e-03  4.74045864e-03  1.03819812e-02  1.40069739e-02
  6.42913682e-03  9.30318956e-03  1.51205450e-02 -3.51888242e-03
  3.95864802e-04  4.84290460e-03 -5.23806713e-03  5.24346292e-03
  1.09526776e-02  5.72491104e-03 -1.93599961e-03  7.38798249e-03
  7.03674246e-03  2.13899052e-03  3.74871380e-03  7.97366404e-03
  6.39685254e-03 -5.45147351e-03  4.41719772e-03 -9.70698750e-03
  2.47353778e-03  2.47938133e-03 -2.14644217e-03  6.97398892e-03
  4.37190089e-01  7.63980081e-03 -3.40450704e-03 -6.64818167e-04
 -7.30157969e-03  1.55370688e-02  8.00499300e-03  2.08649324e-03
  1.71024798e-01  1.70830669e-01  3.14340446e-03  6.42753901e-03
 -4.25200387e-03  6.07810319e-03  2.84069758e-03 -4.77014220e-03
  8.92603461e-03  6.01479318e-03  2.14635363e-02 -8.32712250e-03
 -7.49406068e-03 -6.18142260e-03  6.53842970e-01  3.98287124e-05
  1.95195447e-01  4.34078959e-03  4.12799949e-01  8.89834168e-03
  5.94000854e-03  1.22593934e-05  7.98433145e-03  6.65294685e-01
  1.00000000e+00  6.40248701e-03  7.18778219e-03  4.77050901e-03
  8.17194436e-01]

In [31]:
sorted_index_array = np.argsort(corr_recomienda_serv)
sorted_array = corr_recomienda_serv[sorted_index_array]
rslt = sorted_array[-11 : -1][::-1]
best_rest = sorted_index_array[-11 : -1][::-1]
print("{} mejores calificaciones:".format(10),
      rslt)
print("{} mejores restaurantes:".format(10),
      best_rest)

10 mejores calificaciones: [0.77296036 0.60016191 0.51874979 0.4212561  0.36593986 0.23075355
 0.2262871  0.19289773 0.18292812 0.1788166 ]
10 mejores restaurantes: [58 60 85 97 46 11 55 21 54 29]

In [32]:
sub_reco_service = list(names[best_rest])
print(sub_reco_service)

['Restaurant Teely', 'Restaurant and Bar and Clothesline Carlos N Charlies', 'Rincon del Bife', 'Vips', 'Paniroles', 'Chilis Cuernavaca', 'Restaurant Las Mananitas', 'Giovannis', 'Restaurant Familiar El Chino', 'Kiku Cuernavaca']

Conclusiones: Si bien existen coincidencias con las primeras recomendaciones, existen recomendaciones adicionales por los comensales que disfrutan del servicio de la misma manera que Subway e.g. Kiku Cuernavaca. Además los restaurantes pueden variar de posición por una mejor nota en comida que en comida e.g. Restaurant and Bar and Clothesline Carlos N Charlies.

#**Ejercicio-8.**

Conclusiones: Los sistemas de recomendación son mecanismos sencillos que permiten generar una salida no supervisada de la misma manera que un problema de aprendizaje supervisado de clasificación funcionaría. Sin lugar a duda comparte los mismos principios matemáticos que los demás modelos. En algún momento este modelo se puede convertir en uno supervisado si se utiliza un mecanismo de calibración con comensales experimentados que califiquen las recomendaciones y de esta manera obtener etiquetas para iteraciones en modelos supervisados.

###**Fin de la Actividad de la semana 10 - Sistemas de Recomendación y Reducción de Dimensionalidad con SVD.**